// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStore.Data;

#nullable disable

namespace PetStore.Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PetStore.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PetStore.CatFood", b =>
                {
                    b.HasBaseType("PetStore.Product");

                    b.Property<bool>("KittenFood")
                        .HasColumnType("INTEGER");

                    b.ToTable("CatFoods", (string)null);
                });

            modelBuilder.Entity("PetStore.DogLeash", b =>
                {
                    b.HasBaseType("PetStore.Product");

                    b.Property<int>("LengthInches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.ToTable("DogLeashes", (string)null);
                });

            modelBuilder.Entity("PetStore.CatFood", b =>
                {
                    b.HasOne("PetStore.Product", null)
                        .WithOne()
                        .HasForeignKey("PetStore.CatFood", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetStore.DogLeash", b =>
                {
                    b.HasOne("PetStore.Product", null)
                        .WithOne()
                        .HasForeignKey("PetStore.DogLeash", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
